# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        #Symfony\Component\Security\Core\User\User: bcrypt
        PasswordManager\Bundle\UserBundle\Entity\User: sha512

    role_hierarchy:
     # admin user inherited role user
      ROLE_USER:        [ROLE_USER]
      ROLE_ADMIN:       [ROLE_ADMIN, ROLE_MODERATEUR]
      ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        app_users:
            id: app.provider.ldap
        main:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
             pattern:   ^/
             anonymous: true
             provider: app_users
             # csrf_token_generator: security.csrf.token_manager
             form_login_ldap:
                     service: app.ldap
                     dn_string: uid={username},OU=people,O=Wanadev,DC=wanadev,DC=org
                     check_path: fos_user_security_check
                     login_path: fos_user_security_login
                     default_target_path: /
             form_login:
                     login_path: fos_user_security_login
                     check_path: fos_user_security_check
             logout:
                 path:    fos_user_security_logout
                 target: fos_user_security_login
             remember_me:
               secret:   "%secret%"
               lifetime: 3600000


            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~
            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
    #acl:
    #    connection: default

    access_control:

              - { path: /admin, roles: ROLE_ADMIN }
              - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: http }
           # - { path: ^/admin, roles: ROLE_ADMIN }
      #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
