<?php

namespace PasswordManager\Bundle\UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

class UserRepository extends \Doctrine\ORM\EntityRepository
{


    public function getGroupWithUser(){

        $qb = $this->createQueryBuilder('u');

        $qb->join('u.groups', 'usrGroup')->addSelect('usrGroup');

        return $qb->getQuery()->getResult();

    }

}
