<?php

namespace PasswordManager\Bundle\CoreBundle\Entity;

/**
 * CategoryContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryContactRepository extends \Doctrine\ORM\EntityRepository
{
}
