<?php

namespace PasswordManager\Bundle\PlatformBundle\Repository;

/**
 * AdvertRepositoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepositoryRepository extends \Doctrine\ORM\EntityRepository
{
}
