<?php

namespace PasswordManager\Bundle\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * advertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class advertRepository extends \Doctrine\ORM\EntityRepository
{
}
